machines:
  - id: fio01
    enabled: !!bool true
    type: l99.driver.factoryio.FactoryioLocalMachine, factoryio
    strategy: l99.driver.factoryio.collectors.BasicLocal01, factoryio
    handler: l99.driver.factoryio.handlers.SplunkMetric, factoryio
    
    broker:
      enabled: !!bool true
      net_ip: 10.20.30.102
      net_port: !!int 1883
      auto_connect: !!bool true
      publish_status: !!bool true
      publish_arrivals: !!bool true
      publish_changes: !!bool true
      publish_disco: !!bool true
      disco_base_topic: factoryio
      anonymous: !!bool true
      user: admin
      password: password
      
    l99.driver.factoryio.collectors.BasicLocal01, factoryio:
      sub_topic: factoryio/fio01/io
      
    l99.driver.factoryio.FactoryioLocalMachine, factoryio:
      sweep_ms: !!int 100
      
    l99.driver.factoryio.FactoryioRemoteMachine, factoryio:
      sweep_ms: !!int 1000
      net_uri: http://localhost:7410
      net_timeout_s: !!int 3